# Generated by Django 5.0.6 on 2024-06-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/slider_imgs')),
                ('Discount_Deal', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arivals', 'New Arivals')], max_length=100)),
                ('Sale', models.IntegerField()),
                ('Brand', models.CharField(max_length=200)),
                ('Discount', models.ImageField(upload_to='')),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
    ]
