# Generated by Django 5.0.6 on 2024-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Discount',
            field=models.IntegerField(),
        ),
    ]
