# Generated by Django 5.0.6 on 2024-06-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_slider_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='Brand',
            new_name='Brand_Name',
        ),
    ]
