# Generated by Django 5.0.6 on 2024-07-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_colour_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.colour'),
        ),
    ]
