# Generated by Django 5.0.6 on 2024-07-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
