# Generated by Django 5.0.6 on 2024-07-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_order_shipping_cost_remove_order_tax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
