# Generated by Django 5.0.6 on 2024-07-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='image_url',
            new_name='images',
        ),
    ]
