# Generated by Django 5.0.6 on 2024-07-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_image_url_product_image_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='images',
            new_name='image_url',
        ),
    ]
