# Generated by Django 5.0.6 on 2024-07-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_area',
            name='Link',
        ),
    ]
