# Generated by Django 5.0.6 on 2024-07-20 07:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_banner_area_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
