# Generated by Django 5.0.6 on 2024-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_product_average_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
