# Generated by Django 5.0.6 on 2024-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_order_payment_id_order_payment_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
