# Generated by Django 5.0.6 on 2024-10-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_product_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_area',
            name='Link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
