# Generated by Django 5.0.6 on 2024-10-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_banner_area_link_alter_banner_area_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_Code',
        ),
    ]
