# Generated by Django 5.0.6 on 2024-11-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_product_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='courser_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/course_banner_img')),
                ('Course', models.CharField(max_length=100)),
                ('Quotes', models.CharField(max_length=100)),
                ('Link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
