# Generated by Django 5.0.6 on 2024-11-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_courser_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courser_banner',
            new_name='course_banner',
        ),
    ]
